### ISSUE TITLE
Question about observed in Test_sample_prior.ipynb

### ISSUE THREAD

**Issue by rpgoldman** [junpenglao/Planet_Sakaar_Data_Science#1]
In block 3 in this notebook, you take samples from the prior.  One thing I don't understand is that in that model, there are observed values for the `x_obs` random variable:
```
    pm.Normal('x_obs', mu=mu, sd=1, observed=observed) 
```
Do those impact the sampling from the prior in some way? Are you doing something like rejection sampling here, and keeping only samples that agree with the observations?  Or is that just left around from copying some other code into the notebook?
Thanks!

**Comment by junpenglao** [comment]
> Do those impact the sampling from the prior in some way?

No, the aim of sample prior function is to perform forward pass and ignore the observed. Putting the `observed=observed` there is to make sure the function ignores the observed properly.

**Comment by rpgoldman** [comment]
Ah!  Thank you very much for clarifying that. That makes perfect sense!
