### ISSUE TITLE
LKJCholeskyCov(): Is compute_corr parameter still supported?

### ISSUE THREAD

**Issue by marcusrichards** [junpenglao/Planet_Sakaar_Data_Science#2]
`with pm.Model() as model:
    sd_dist = pm.Exponential.dist(1.0)
    chol, corr, sigmas = pm.LKJCholeskyCov('chol_cov', eta=4, n=10,
    sd_dist=sd_dist, compute_corr=True)`

Yields the following error:
`TypeError: __init__() got an unexpected keyword argument 'compute_corr'`

In the PyMC3 source code it is not listed as a parameter.

If this is no longer supported, is there a simple method for obtaining the corr and sigmas from the cholesky?

many thanks
Marcus

**Comment by junpenglao** [comment]
`compute_corr` is a new feature: https://github.com/pymc-devs/pymc3/blob/5ffba858c69e37a0934fc4daa4a4b62082a96948/pymc3/distributions/multivariate.py#L1143-L1145
You can update to the latest release or master branch.
